
- hosts: new
  become: yes
  tasks:
  - name: Getting Code from get.docker.com 
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -	
  - name: repo	
    shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - name: update	
    shell: sudo apt update
  - name: Policy
    shell: apt-cache policy docker-ce	
    register: policy
  - name: Print Policy
    debug:
      var: policy.stdout_lines
  - name: Installation
    shell: sudo apt install docker-ce -y
  - name: user docker
    shell: sudo usermod -aG docker ubuntu
