- hosts: self
  become: yes
  tasks:
  - name: Remove maven existed zip file
    file:
      path: /opt/apache-maven-3.8.4-bin.zip
      state: absent
  - name: Remove maven existed folder in home location
    file:
      path: /home/ansible/apache-maven-3.8.4
      state: absent
  - name: Remove maven existed folder in opt location
    file:
      path: /opt/apache-maven-3.8.4
      state: absent
  - name: Download Maven
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip
      dest: /opt/apache-maven-3.8.4-bin.zip
  - name: Unzipping Maven
    shell: sudo unzip /opt/apache-maven-3.8.4-bin.zip
  - name: Moving
    shell: mv /home/ansible/apache-maven-3.8.4 /opt/
  - name: Addind Lines
    lineinfile:
      dest=/home/ansible/.bash_profile
      line="{{ item.line }}"
      state=present
    with_items:
      - { line: '$PATH=$HOME/bin' }
      - { line: 'export PATH' }
      - { line: 'export M2_HOME=/opt/apache-maven-3.8.4' }
      - { line: 'export PATH=$PATH:$M2_HOME/bin' }
  - name: Print Maven Installation Details
    debug:
      msg: "Maven Installed Successfully"

