#ansible-playbook nexus.yml --tags install
#ansible-playbook nexus.yml --tags stop
#- hosts: 172.31.2.28

- hosts: 172.31.9.154
  become: yes
  vars:
    prt: 8085
  tasks:
  - name: install open JDK
    tags:
    - install
    yum:
      name: java-11-openjdk-devel
      state: present
  - name: Remove Nexus file
    shell: rm -rf /opt/nexus
    tags:
    - install
  - name: Download nEXUS
    get_url:
      url: http://download.sonatype.com/nexus/3/nexus-3.36.0-01-unix.tar.gz
      dest: /opt/nexus-3.36.0-01-unix.tar.gz
    tags:
    - install
  - name: Extract nexus
    unarchive:
      src:  /opt/nexus-3.36.0-01-unix.tar.gz    
      dest: /opt/
      remote_src: yes
    tags:
    - install
  - name: Renaming nexus file
    tags:
    - install
    shell: mv /opt/nexus-3.36.0-01 /opt/nexus
  - name: userdel nexus
    tags:
    - install
    shell: userdel nexus
  - name: useradd nexus
    tags:
    - install
    shell: useradd nexus
  - name: line add in visudo
    tags:
    - install
    lineinfile:
      path: /etc/sudoers
      line: 'nexus        ALL=(ALL)       NOPASSWD: ALL'
      insertbefore: EOF
  - name: chown
    tags:
    - install
    shell: chown -R nexus:nexus /opt/sonatype-work
  - name: chown
    tags:
    - install
    shell: chown -R nexus:nexus /opt/nexus 
  - name: chmod
    tags:
    - install
    shell: chmod -R 775 /opt/nexus  
  - name: chmod
    tags:
    - install
    shell: chmod -R 775 /opt/sonatype-work
  - name: run_as_user parameter
    tags:
    - install
    lineinfile:
      path: /opt/nexus/bin/nexus.rc
      line: run_as_user="nexus" 
  - name: Remove nexus as a service
    tags:
    - install
    shell: sudo rm -rf /etc/init.d/nexus
    become_user: nexus
  - name: Create nexus as a service
    tags:
    - install
    shell: sudo ln -s /opt/nexus/bin/nexus /etc/init.d/nexus
  - name: change port of Nexus from 8081 to {{prt}}
    tags:
    - install
    replace:
      regexp: application-port=8081
      replace: application-port={{prt}}
      path: /opt/nexus/etc/nexus-default.properties
  - name: Enable the nexus services
    tags:
    - install
    shell: sudo systemctl enable nexus.service
    become_user: nexus
  - name: Start the nexus service
    tags:
    - start
    shell: sudo systemctl start nexus 
    register: nexstart
    become_user: nexus
 
  - name: Print Nexus Start Status
    tags:
    - start
    debug:
      var: nexstart
  - name: Status of the nexus service
    tags:
    - status
    shell: sudo systemctl status nexus
    register: nexstatus
  - name: Print Nexus Status
    tags:
    - status
    debug:
      var: nexstatus
  - name: Stop the nexus service
    tags:
    - stop
    shell: sudo systemctl stop nexus.service
    register: nexstop
  - name: Print Nexus Stop Status
    tags:
    - stop
    debug:
      var: nexstop

