
- hosts: self
  become: yes
  tasks:
  - name: UnInstall nginx
    yum:
      name: nginx
      state: absent
      autoremove: yes 
  - name: remove html folder
    file:
      path: /usr/share/nginx/html/
      state: absent
